### ISSUE TITLE
Exclude kotlin-stdlib-js from the build and publish to both maven and npm

### ISSUE THREAD

**Issue by mxj4** [daemontus/kotlin-ace-wrapper#1]
Thanks for the work, I'm experimenting Kotlin and Ace in my frontend project and would like to use it.

I found the build script will try to compile kotlin-std-js instead of depending on pre-built library, I also need the wrapper packaged as NPM modules. Can we have this wrapper built in a similar way as https://github.com/JetBrains/kotlin-wrappers and publish to both NPM and Maven? I can help changing the build scripts.

**Comment by daemontus** [comment]
Hi, thanks for the feedback! 
 - I'll have a look at the dependency issue as soon as possible... (I should have some time before the end of the week)
 - As for Maven, for now, you can just use Jitpack - it's a classic maven repository, if you click the version badge in readme, you'll find an example of how to add the project as a maven dependency. In the future, if more people use this, I'll be happy to move this to something more stable like bintray, but right now this is a simple, fast and effective solution.
 - As for NPM, it's been a while since I've worked with JS community, but I think I should be able to set-up NPM publishing based on the kotlin-wrappers repository. If I have some problems, I'll let you know and maybe you can help :)

I'll get back to you by the end of the week about the progress. Cheers!

**Comment by daemontus** [comment]
Hi, first of all, sorry it took so long (summer, vacation, other projects, you know the drill).

However, the issues should be fixed now:
 - everything is published to npm
 - for maven, use jitpack
 - the library has been updated to support kotlin frontend plugin and webpack for easier builds/bundling.

If there is any other problem, let me know :)
